### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by ycaxgjd**

### CODE REVIEW

**Comment by martinezmatias** [comment]
Hi @ycaxgjd 
Does it work the deployment?
I could not find the artifact https://mvnrepository.com/search?q=fr.inria.coming.Coming 
(Maybe I have to wait some hours)
Thanks!
Regards
Matias

**Comment by ycaxgjd** [comment]
Hey, @martinezmatias. This is one PR build so the deployment was skipped.

**Comment by ycaxgjd** [comment]
This time, I commented the skip-deployment rule for PR build.

**Comment by ycaxgjd** [comment]
I checked the CI log and found "iv undefined". This message means `deploy_to_maven.sh` interrupted at [line 26](https://github.com/SpoonLabs/coming/blob/master/.buildscript/deploy_to_maven.sh#L26)

Hey @martinezmatias, I guess this issue should be about CI Environment Variables, please check.

**Comment by martinezmatias** [comment]
Hi @ycaxgjd 
When I created the script `deploy_to_maven.sh` I could not do it work.
I imagine that the issue is related to the fact that the repo is SpoonLabs and the keys are upload to my account. So, Travis checks on Spoonlabs and then fails (but not sure about the real problem)

**Comment by ycaxgjd** [comment]
Hey @martinezmatias, I am not sure. But I guess maybe we just lose one CI Environment Variable named "encrypted_9809c3ea697e_iv". Both KEY and IV are used in AES but it seems that KEY exists and IV not exists. Please help check the setting option in Coming CI build page. Or compare with the setting option of GTSpoon CI. I am not able to check them as I have no access.

**Comment by martinezmatias** [comment]
Hi @ycaxgjd 
As I am not in the list of Coming's collaborator, I cannot add those keys in the Travis' configuration.
I've just asked Martin about.

**Comment by martinezmatias** [comment]
One of the  tutorial I have started when I started with this issue following is: https://www.phillip-kruger.com/post/continuous_integration_to_maven_central/

**Comment by ycaxgjd** [comment]
Hey @martinezmatias, I checked the CI Environment Variables setting and env-variables are not there. Could you add them if you have keys in hand?

**Comment by martinezmatias** [comment]
Sorry, I am not sure in which step you are (I am a bit lost), we should re synchronise

**Comment by ycaxgjd** [comment]
Hey @martinezmatias I am also lost. Maybe we could learn from the Environment Variables settings of GTSpoon.

**Comment by ycaxgjd** [comment]
Hey @martinezmatias, based on line 429-437 at [the latest CI build log of GTSpoon](https://travis-ci.org/SpoonLabs/gumtree-spoon-ast-diff/builds/544268855?utm_source=github_status&utm_medium=notification), we should add env-variables as follows:
1. add `encrypted_xxx_key` and `encrypted_xxx_iv` at [the CI settings page of Coming](https://travis-ci.org/SpoonLabs/coming/settings)
2. add `CI_DEPLOY_PASSWORD` and `CI_DEPLOY_USERNAME` at [`.travis.yml` of Coming](https://github.com/SpoonLabs/coming/blob/master/.travis.yml). Just like [that of GTSpoon](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/.travis.yml#L4)

In case you do not have `encrypted_xxx_key` and `encrypted_xxx_iv`, please see [this tutorial](http://www.debonair.io/post/maven-cd/).

**Comment by martinezmatias** [comment]
Hi @ycaxgjd 
I will do it now

**Comment by martinezmatias** [comment]
I am quite complicated today, you can proceed and then send me with the data to put in the configuration's page of Travis via email.

**Comment by ycaxgjd** [comment]
Hey @martinezmatias, I have done Step2. I guess you have `encrypted_xxx_key` and `encrypted_xxx_iv` in hand, if so, we just need to put them in the configuration's page of Travis.

As `encrypted_xxx_key` and `encrypted_xxx_iv` should have been generated with the correct `signingkey.asc`, I have no way to do Step1.

**Comment by martinezmatias** [comment]
Almost done

**Comment by martinezmatias** [comment]
Hi @ycaxgjd 
Pushed.
Crossed fingers!
Thanks a lot for the great work.

**Comment by ycaxgjd** [comment]
Hey @martinezmatias, please help in Step1. I thought encrypted values of both `CI_DEPLOY_USERNAME` and `CI_DEPLOY_PASSWORD` are only related to their actual values, so I just copied them from GTSpoon. Actually, they should be regenerated in each different project, even with same username and password.

Please execute following commands __at the root directory of this project__ to complete Step1:
```bash
travis encrypt CI_DEPLOY_USERNAME=xxxxxxxx --add
```
```bash
travis encrypt CI_DEPLOY_PASSWORD=xxxxxxxx --add
```
In case you have no `travis` in shell, install it by `gem install travis`.

**Comment by martinezmatias** [comment]
Hi @ycaxgjd 
I imagine that those User/Password correspond to a Sonatype account. Right?
It seems that is necessary to apply the steps described here: https://www.phillip-kruger.com/post/continuous_integration_to_maven_central/ (Step Sonatype Nexus OSS).
Do you agree?

**Comment by ycaxgjd** [comment]
Hey @martinezmatias I agree.

**Comment by martinezmatias** [comment]
Hi @ycaxgjd 
As mentioned in the tutorial, I created the issue:
https://issues.sonatype.org/browse/OSSRH-49772

**Comment by ycaxgjd** [comment]
Hey @martinezmatias, you get one [comment](https://issues.sonatype.org/browse/OSSRH-49772?focusedCommentId=735443&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-735443).

**Comment by martinezmatias** [comment]
Hi @ycaxgjd  
Yes, I was discussing with Martin the steps to follow.
We will rename the groupId from Coming's pom.

**Comment by martinezmatias** [comment]
Hi @ycaxgjd 
I added the encrypted keys corresponding to vars `CI_DEPLOY_USERNAME` and  `CI_DEPLOY_PASSWORD`. https://github.com/SpoonLabs/coming/commit/7b5d9ebfe4e0283db255daec26c60f96fa51d64b

**Comment by ycaxgjd** [comment]
Hey @martinezmatias, right now CI would fail in timeout waiting for one passphrase. Maybe we made some mistakes in Step2, as I found our [encrypted values](https://github.com/SpoonLabs/coming/blob/master/.travis.yml#L16) of both `CI_DEPLOY_USERNAME` and `CI_DEPLOY_PASSWORD` are much longer than [these](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/.travis.yml#L4) in GTSpoon.

**Comment by jaxxgu** [comment]
Hey @martinezmatias, we should have to append one extra encrypted key `PASSPHRASE` to `.travis.yml`, besides `CI_DEPLOY_USERNAME` and `CI_DEPLOY_PASSWORD`. [This tutorial](http://www.debonair.io/post/maven-cd/) should be meaningful for reference, also one related [example repo](https://github.com/stefanbirkner/travis-deploy-to-maven-central).

Here are related messages from CI build log
```
You need a passphrase to unlock the secret key for
user: "martinezmatias <matomartinez@gmail.com>"
2048-bit RSA key, ID 10CD611C, created 2019-02-22

Enter passphrase:
```
```
gpg: gpg-agent is not available in this session

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by martinezmatias** [comment]
Hi @jaxxgu 
Sorry for the delay, I was traveling last two weeks.
I have updated the travis file by adding the encrypted passphrase.
However it still fails.
Now, I am checking for the second problem: `gpg: gpg-agent is not available in this session`

**Comment by martinezmatias** [comment]
Hi @jaxxgu 
I cannot solve this issue. 
I follow step-by-step the tutorial and it's not working.
Now I cannot decrypt the encrypted certificate:
 
https://travis-ci.org/SpoonLabs/coming/jobs/560546866
```
bad decrypt
139630361597600:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:evp_enc.c:539:
The command ".buildscript/deploy_to_maven.sh" failed and exited with 1 during .
```

**Comment by jaxxgu** [comment]
Hey @martinezmatias
What is the difference between `signingkey.asc` and `codesigning.asc`?

**Comment by martinezmatias** [comment]
I recreated the keys to see if I could fix the problems, I used the same name than k. The tutorial
________________________________

**Comment by jaxxgu** [comment]
Hey @martinezmatias
Before that, could you please append the encrypted value of PASSPHRASE for `signingkey.asc` into `.travis.yml`. We are very close to success, and I also feel the second issue `gpg: gpg-agent is not available in this session` should be caused by the first issue of lacking passphrase.

**Comment by jaxxgu** [comment]
Hey @martinezmatias 
Ping~

**Comment by martinezmatias** [comment]
Hi @jaxxgu 
I'm back, I was offline some days

**Comment by martinezmatias** [comment]
Hi @jaxxgu 
A summary:
I regenerated a new key [(codesigning)](https://github.com/SpoonLabs/coming/blob/mavencentraldeploysign/.buildscript/codesigning.asc.enc) which is encrypted. Then, the script https://github.com/SpoonLabs/coming/blob/mavencentraldeploysign/.buildscript/deploy_to_maven.sh#L28 decrypt this key.
In the [travis](https://github.com/SpoonLabs/coming/blob/mavencentraldeploysign/.travis.yml#L3) I added different values:
PASSPHRASE with the passphrase of  codesigning and the four that we have in the tutorial (CI_DEPLOY_USERNAME, CI_DEPLOY_PASSWORD, GPG_KEY_NAME and GPG_PASSPHRASE).
WDYT?
Thanks!
Matias

**Comment by jaxxgu** [comment]
Hey @martinezmatias, is there the encrypted value of `PASSPHRASE` for `signingkey.asc` in __mavencentraldeploysign__ branch? I want to try to add that into the __master__ branch.

**Comment by martinezmatias** [comment]
Hi @jaxxgu 
The PASSPHRASE should be the same either for both signingkey.asc and codesigning.asc (this later is product of my second attempt following the instructions)

**Comment by jaxxgu** [comment]
Hey @martinezmatias 
I tried `codesigning.asc` but failed at the __`openssl ...`__ step. The reason is that we have to run __`travis encrypt-file codesigning.asc -r SpoonLabs/coming --add`__ again to generate new `key` and `iv` instead of using `encrypted_a263e63e6aa6_key` and `encrypted_a263e63e6aa6_iv` directly.

Please help generate new `key` and `iv` and replace old values, both in CI setting page and `deploy_to_maven.sh`.

**Comment by martinezmatias** [comment]
Hi @jaxxgu
I reexecuted the command
```
 travis encrypt-file ./.buildscript/codesigning.asc -r SpoonLabs/coming --add
```
but I generates the same output i.e., the command to put in the travis:
```
- openssl aes-256-cbc -K $encrypted_a263e63e6aa6_key -iv $encrypted_a263e63e6aa6_iv
  -in codesigning.asc.enc -out ./.buildscript/codesigning.asc -d
```
See that the new key values are the same.
However, I dont remember how to to the step related to the CI setting.
There, we have two variables `encrypted_a263e63e6aa6_iv` and `encrypted_a263e63e6aa6_key` which would be the values? (I dont remember that I step when I did some weeks ago and I cannot find it in the documentation)
Thanks
Matias

**Comment by jaxxgu** [comment]
Hey @martinezmatias 
Here is the [link to CI setting page](https://travis-ci.org/SpoonLabs/coming/settings). If values are same, it becomes hard to know its cause.

Unlike `codesigning.asc`, for `signingkey.asc`, we only fail at the last step for the lacking of `PASSPHRASE`. Is it possible to generate `PASSPHRASE` of `signingkey.asc` one more time?

Or else maybe we could try to deploy to maven manually to make sure all steps being correct, then turn to the automated way.

**Comment by martinezmatias** [comment]
Hi @jaxxgu 
> Is it possible to generate PASSPHRASE of signingkey.asc one more time?

Question to be sure: here I use the `password` related to this key. Do you agree?

**Comment by martinezmatias** [comment]
> Here is the link to CI setting page. If values are same, it becomes hard to know its cause.
My doubt there is *what*  is the `value` of those variables. Is the command `travis encrypt-file` who puts the variable-values there, right?

**Comment by jaxxgu** [comment]
If you execute `travis encrypt-file xxx --add` command at the root directory of project, one `xxx.enc` file would be generated.

If you execute `travis encrypt aaa=bbb --add` command then one text like `secure: "... encrypted data ..."` will be appended into `.travis.yml`.

I put environment-variables into CI setting page always via web-interface, do not know whether there is one command-way.

**Comment by martinezmatias** [comment]
> If you execute travis encrypt-file xxx --add command at the root directory of project, one xxx.enc file would be generated.

Exact. The generated file is here: https://github.com/SpoonLabs/coming/blob/master/.buildscript/codesigning.asc.enc 

> If you execute travis encrypt aaa=bbb --add command then one text like secure: "... encrypted data ..." will be appended into .travis.yml.

Yes, using that command I encrypted the PARAPHASSE, and the CI user and password.

> I put environment-variables into CI setting page always via web-interface, do not know whether there is one command-way.

What it is not clear for me is the value we put for those variables (encrypted_a263e63e6aa6_key) via web-interface

**Comment by jaxxgu** [comment]
Hey @martinezmatias 
Based on this [documentation](https://github.com/travis-ci/travis.rb/blob/master/README.md#encrypt-file), `key` and `iv` are corresponding values used in the step of executing `travis encrypt-file xxx` command. If they are not specified at that step, they would be generated randomly.

If `codesigning.asc` was encrypted without specific options of `key` and `iv`, then newly generated `key` and `iv` would be written to the CI setting page automatically. In this case, we just need to replace `encrypted_a263e63e6aa6_key` and `encrypted_a263e63e6aa6_iv` with newly generated `encrypted_xxxxxx_key` and `encrypted_xxxxxx_iv`, at `.travis.yml`.

**Comment by martinezmatias** [comment]
Hi @jaxxgu 

> with newly generated encrypted_xxxxxx_key and encrypted_xxxxxx_iv, at .travis.yml.

I agree with you, but we run `travis encrypt-file xxx --add ` it addes to .travis.yml both encrypted_a263e63e6aa6_key and encrypted_a263e63e6aa6_iv.

Maybe a solution could be to manually remove those variables from the Travis's site.
WDYT?

**Comment by jaxxgu** [comment]
Hey @martinezmatias 
My mistake, it should be `deploy_to_maven.sh`, not `.travis.yml`. Actually, `encrypted_xxxxxx_key` and `encrypted_xxxxxx_iv` should never appear at `.travis.yml`.

I removed variables from the Travis's site. Could you please try these steps at __master__ branch directly?

**Comment by martinezmatias** [comment]
Hi @jaxxgu 

> My mistake, it should be deploy_to_maven.sh, not .travis.yml. Actually, encrypted_xxxxxx_key and encrypted_xxxxxx_iv should never appear at .travis.yml.

But I imagine that is the same, because travis.yml calls to deplot_to_maven.sh. (And in fact the travis command adds it to .travis.yml). In any case, I will add it to deploy_to_maven.

> I removed variables from the Travis's site. Could you please try these steps at master branch directly?

I do it right now.

**Comment by martinezmatias** [comment]
pushed.
updated deploy_to_maven.sh and codesigning.asc.
However, encrypted_xxxxxx_key and encrypted_xxxxxx_iv at deploy_to_maven.sh (generated by travis) are always the same.

**Comment by jaxxgu** [comment]
Hey @martinezmatias 
We do not have the values of `encrypted_xxxxxx_key` and `encrypted_xxxxxx_iv` now. Could you please add them manually to the [CI setting page](https://travis-ci.org/SpoonLabs/coming/settings)? Maybe they were automatically added to your CI but not SpoonLabs's CI.

Based on this [documentation](https://github.com/travis-ci/travis.rb/blob/master/README.md#encrypt-file), values of `encrypted_xxxxxx_key` and `encrypted_xxxxxx_iv` could get shown by append this option `-p`.

**Comment by martinezmatias** [comment]
Hi @jaxxgu 

> Based on this documentation, values of encrypted_xxxxxx_key and encrypted_xxxxxx_iv could get shown by append this option -p.

Good point! I have them. I add them now.

**Comment by martinezmatias** [comment]
Added into Travis values for `encrypted_a263e63e6aa6_iv` and `encrypted_a263e63e6aa6_key`

**Comment by jaxxgu** [comment]
Hey @martinezmatias 
I tried to solve the new issue about `bad decrypt`, but I can not solve that. One [post](https://stackoverflow.com/questions/39637388/encryption-decryption-doesnt-work-well-between-two-different-openssl-versions) on StackOverflow looks related, WDYT?

Maybe we could try to deploy to maven manually at first, ignoring all unnecessary steps.

**Comment by jaxxgu** [comment]
Hey @martinezmatias 
WDYT?

**Comment by martinezmatias** [comment]
Hi @jaxxgu 
I will redo all the step from a Linux instead from my mac.

**Comment by martinezmatias** [comment]
Hi @jaxxgu 
It seems we have good news: https://api.travis-ci.org/v3/job/566514949/log.txt

Run deploy_to_maven
Deploying ...
OpenSSL 1.0.1f 6 Jan 2014
Before gpg
gpg: key 6BF3EB8E: public key "Matias Martinez (none) <matomartinez@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
After gpg

Now, let's see the deployment :)

**Comment by jaxxgu** [comment]
👍Really one amazing good news!

**Comment by jaxxgu** [comment]
I found the ERROR messages at the ending part. Is it because of gpg2, like this [post](https://dingyichen.wordpress.com/2017/08/30/gpg-no-default-secret-key-gpg/) and this [post](https://superuser.com/questions/1112673/gpg2-no-secret-key)?

**Comment by martinezmatias** [comment]
I am trying to fix it, maybe is due to the var name used:
https://github.com/SpoonLabs/coming/commit/9eddb1158c2f465e5292c5204f12ae8f251e57dd
(I have not encrypted for PASSPHRASE

**Comment by martinezmatias** [comment]
It's strange:
In this tutorial https://github.com/making/travis-ci-maven-deploy-skelton it also encrypts the secret key

**Comment by jaxxgu** [comment]
Hey, is this [step](https://github.com/stefanbirkner/travis-deploy-to-maven-central#create-gpg-keys) same with yours?

**Comment by martinezmatias** [comment]
Yes

**Comment by martinezmatias** [comment]
Now I change the settings.xml (according to http://www.debonair.io/post/maven-cd/)
 <gpg.executable>gpg</gpg.executable>

**Comment by martinezmatias** [comment]
But it is still failing

**Comment by martinezmatias** [comment]
I re push. Let's see

**Comment by martinezmatias** [comment]
Partially solved. 
Now: 
gpg: no default secret key: bad passphrase
gpg: signing failed: bad passphrase

**Comment by martinezmatias** [comment]
We process (slowly).
Now We have: 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project coming: Execution sign-artifacts of goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign failed: Plugin org.apache.maven.plugins:maven-gpg-plugin:1.6 or one of its dependencies could not be resolved: Could not transfer artifact org.codehaus.plexus:plexus-utils:jar:3.0.20 from/to central (https://repo.maven.apache.org/maven2): GET request of: org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar from central failed: Tag mismatch! -> [Help 1]

**Comment by jaxxgu** [comment]
This error seems one strange accidental event.

It is [build#606](https://travis-ci.org/SpoonLabs/coming/builds/566844880?utm_source=github_status&utm_medium=notification), and when I rebuild, it becomes _`gpg: no default secret key: bad passphrase`_ again.

**Comment by jaxxgu** [comment]
This error seems one strange accidental event.

It is [build#606](https://travis-ci.org/SpoonLabs/coming/builds/566844880?utm_source=github_status&utm_medium=notification), and when I restart build, it becomes _`gpg: no default secret key: bad passphrase`_.

**Comment by jaxxgu** [comment]
Hey @martinezmatias 
I found that more than one secret key exists in travis
```
do we have more than one secret key?
/home/travis/.gnupg/pubring.gpg
-------------------------------
pub   4096R/3804BB82D39DC0E3 2014-10-28
uid                          Michal Papis (RVM signing) <mpapis@gmail.com>
uid                          Michal Papis <michal.papis@toptal.com>
uid                          [jpeg image of size 5015]
sub   2048R/85BB5679C71866D7 2015-11-02

pub   4096R/B0DB49596BF3EB8E 2019-08-01
uid                          Matias Martinez (none) <matomartinez@gmail.com>
sub   4096R/62530FEF27E2A654 2019-08-01
```
This might be the cause of the _`gpg: no default secret key: bad passphrase`_ error

**Comment by martinezmatias** [comment]
Hi @jaxxgu 

> do we have more than one secret key?

No, only one,  this is the ouput of such command on my machine: 

Matiass-MacBook-Pro:coming matias$  gpg --keyid-format LONG -k
/Users/matias/.gnupg/pubring.kbx
--------------------------------
pub   rsa4096/B0DB49596BF3EB8E 2019-08-01 [SC]
      ADXXXXXXXXXXXXX
uid                [ inconnue] Matias Martinez (none) <matomartinez@gmail.com>
sub   rsa4096/62530FEF27E2A654 2019-08-01 [S]

**Comment by jaxxgu** [comment]
Hey @martinezmatias 
Messages in that block is from latest log of travis CI, as I updated `deploy_to_maven.sh`. There exists more than one secret key in travis environment.

**Comment by martinezmatias** [comment]
Hi @jaxxgu 
It seems related to the ruby virtual machine:
In the log we can see
```
/home/travis/perl5/perlbrew/bin/perlbrew  - App::perlbrew/0.80
[34m[1mphpenv version[0m
rbenv 1.1.1-25-g6aa70b6
[34m[1mrvm version[0m
rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
[34m[1mdefault ruby version[0m
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
```

**Comment by jaxxgu** [comment]
Is it feasible to delete Michal Papis's public-key and secret-key directly? Or select yours when running `deploy_to_maven.sh`.

**Comment by martinezmatias** [comment]
I dont know, we can try with `gpg --delete-secret-key   mpapis@gmail.com`  and   `gpg --delete-secret-key michal.papis@toptal.com`

**Comment by jaxxgu** [comment]
These commands are interactive, then we have no way to enter "y" when it ask "y/n".

**Comment by martinezmatias** [comment]
Yes, you are right

**Comment by jaxxgu** [comment]
I deleted Michal Papis‘s key, but unfortunately it seems not the real cause. Right now it is still _`gpg: no default secret key: Bad passphrase`_ error.

This is related [build log](https://api.travis-ci.org/v3/job/567379471/log.txt). Besides, Michal Papis‘s key will not be affected permanently as it can restore in new CI builds.

**Comment by martinezmatias** [comment]
I tried with the master key, but it does not work.

**Comment by martinezmatias** [comment]
We have some problems with the decryption of the keys:
```
$ export 71MCNc9JizO2u16I9rlcHCWIhk3GKDBY1RM0eFqi3QrmPrroP4iZlUwcKXQWWFlnHEbbs9ARP4987MQ3zLA44phQ=[secure]
438We were unable to parse one of your secure environment variables.
439Please make sure to escape special characters such as ' ' (white space) and $ (dollar symbol) with \ (backslash) .
440For example, thi$isanexample would be typed as thi\$isanexample. See https://docs.travis-ci.com/user/encryption-keys.
441$ export 12SMhX1U3KuIP1ke2ScTFzKwNT620=[secure]
442We were unable to parse one of your secure environment variables.
443Please make sure to escape special characters such as ' ' (white space) and $ (dollar symbol) with \ (backslash) .
444For example, thi$isanexample would be typed as thi\$isanexample. See https://docs.travis-ci.com/user/encryption-keys.

```

**Comment by martinezmatias** [comment]
(I have sent you an email)

**Pull request merged**
