### PR TITLE
Exception thrown by Operation.toStringAction

### PR DESCRIPTION
**Pull request by khaes-kth**
Hello @martinezmatias @monperrus 

I added a [test case](https://github.com/khaes-kth/coming/blob/revision/FixForExec/src/test/java/fr/inria/coming/spoon/repairability/RepairabilityTest.java#L197) that throws nullpointerexception. Here is the trace:

```
java.lang.NullPointerException
	at gumtree.spoon.diff.operations.Operation.toStringAction(Operation.java:72)
	at gumtree.spoon.diff.operations.Operation.toString(Operation.java:36)
	at java.base/java.lang.String.valueOf(String.java:3352)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:166)
	at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:457)
	at java.base/java.lang.String.valueOf(String.java:3352)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:166)
	at fr.inria.coming.changeminer.analyzer.instancedetector.ChangePatternInstance.toString(ChangePatternInstance.java:87)
	at java.base/java.lang.String.valueOf(String.java:3352)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:166)
	at fr.inria.coming.changeminer.analyzer.instancedetector.DetectorChangePatternInstanceEngine.calculateValidInstancesFromMapping(DetectorChangePatternInstanceEngine.java:96)
	at fr.inria.coming.changeminer.analyzer.instancedetector.DetectorChangePatternInstanceEngine.findPatternInstances(DetectorChangePatternInstanceEngine.java:60)
	at fr.inria.coming.changeminer.analyzer.instancedetector.PatternInstanceAnalyzer.analyze(PatternInstanceAnalyzer.java:67)
	at fr.inria.coming.core.engine.RevisionNavigationExperiment.analyze(RevisionNavigationExperiment.java:123)
	at fr.inria.coming.main.ComingMain.start(ComingMain.java:156)
	at fr.inria.coming.main.ComingMain.run(ComingMain.java:149)
	at fr.inria.coming.spoon.repairability.RepairabilityTest.testNullPointerInDiff(RepairabilityTest.java:204)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

```
I added this request here because I was not sure whether the problem was caused by gumtree-ast-diff or by coming. When, instead of detecting patterns, the diff between two files is computed and printed it does not throw any exceptions, so it might be caused by Coming and not gumtree-ast-diff.

### CODE REVIEW

**Comment by monperrus** [comment]
thanks. why is the diff so big with so many changed files? merge/rebase with master?

**Comment by khaes-kth** [comment]
Hi @monperrus 



> why is the diff so big with so many changed files?

Two reasons: 1- this request also includes some small bug fixes that I applied before running the program on the dataset (commit_id: 
849a885). 2- the PR is made from the same branch as the branch of [this merged PR](https://github.com/SpoonLabs/coming/pull/205). So some of the commits are repeated here (namely, 48839c1 and 9d28fc8) while their changes are already merged into master.

**Comment by monperrus** [comment]
> this request also includes some small bug fixes

could you please put them in a separate PR? that's a good practice.


> So some of the commits are repeated here

With a proper merge/rebase they will not appear. Could you rebase against master?

Thanks!

**Comment by khaes-kth** [comment]
> could you please put them in a separate PR? that's a good practice.

[Done](https://github.com/SpoonLabs/coming/pull/209).



> With a proper merge/rebase they will not appear. Could you rebase against master?

I think rebase does not work in this case.

**Pull request closed without merging**
