### PR TITLE
Ods enum label

### PR DESCRIPTION
**Pull request by SophieHYe**
Hi Matias,

I have updated the ODS labels to enumeration type. Could you please review this version?
Also, I may need your help to update the coming snapshot version to the maven repository for updating repairnators type.
Thanks a lot!

### CODE REVIEW

**Comment by martinezmatias** [comment]
Hi @SophieHYe 
Thanks a lot. Commit a356a35 seems perfect.
However, note that the PR contains commits that we have already merged into the master and we Squash (i.e. to convert all commits into one single) when we merge it (in this one: https://github.com/SpoonLabs/coming/commit/ef0451b97086d803bf954c539b726ca6e0f82d4e).
I imagine that the problem is in you branch [ODSEnumLabel](https://github.com/SophieHYe/coming/commits/ODSEnumLabel) in your origin  which contains commits that the Coming master (your upstream) does not contain because we squashed when we merge.  (The problem could be that you may have done the `pull` from the branch you have done the previous PR. )

I imagine that if we squash it would not be not produce a conflict. @monperrus WDYT? do we squash?

**Comment by SophieHYe** [comment]
Hi Matias,
Ah, I saw the file changes only made on two files for this PR :)
If you prefer, we can close this PR and I will cherry pick the last commit in a new PR?

**Comment by martinezmatias** [comment]
Hi @SophieHYe 
> we can close this PR and I will cherry pick the last commit in a new PR?

Okey, please, thanks!

**Comment by martinezmatias** [comment]
Done in PR #239

**Pull request closed without merging**
