### PR TITLE
[docs] ROLES naming convention

### PR DESCRIPTION
**Pull request by sedflix**
#85 hopefully fixed

### CODE REVIEW

**Comment by martinezmatias** [comment]
Hi @sedflix 

Could you push a test case that asserts the new behaviour?
Thanks
Matias

**Comment by sedflix** [comment]
No changes were made in the source code. It's just he documentation that was changed.
Though we could add a validator for role names while making a change pattern specification?

**Comment by martinezmatias** [comment]
I reeeer to a test case that assert the change of the behaviour related to the file:
src/main/resources/repairability/JMutRepair/binary.xml

**Comment by sedflix** [comment]
Oh! I was thinking about writing the test code for those separately because it is supposed to evaluate the performance of the module and for that, it needs to analyze quite a large number of cases(the DDR patch dataset) and that will make the testing phase really slow. 
What do you think?


Though I will add a small test case of this and the other repair tool I'm working in one of the later PR

**Comment by martinezmatias** [comment]
> Though I will add a small test case of this and the other repair tool I'm working in one of the later PR

Perfect. Thanks!

> What do you think?

As you mention, we can do two tests, one "simpler" for testing this PR.

**Comment by sedflix** [comment]
@martinezmatias Added a test case as suggested by you!
Thanks :D

**Comment by martinezmatias** [comment]
Super! Perfect! Thanks a lot!

**Pull request merged**
