### PR TITLE
Add RepairabilityFilterAnalyzer

### PR DESCRIPTION
**Pull request by sedflix**
Filters

### CODE REVIEW

**Comment by martinezmatias** [comment]
Hi @sedflix 
Thanks a lot for the commit.
I'd propose a small change:
* The name `RepairabilityFilterAnalyzer` is a bit ambiguous because it includes the work 'Filter' (which is another entity of Coming)

**Comment by sedflix** [comment]
Hey @martinezmatias ,
Do you have any keyword in mind with which I can replace filter?

**Comment by martinezmatias** [comment]
Hi @sedflix 
No, but I would remove "Filter" to avoid confusion.

**Comment by martinezmatias** [comment]
Hi @sedflix 
Great! thanks for renaming the class. That would avoid misunderstanding.

**Comment by sedflix** [comment]
Thanks for the suggestions. I didn't think of it before!

**Pull request merged**
