### PR TITLE
WIP add Automatic diff dissection

### PR DESCRIPTION
**Pull request by tdurieux**
Not done, but is it how you would do it?

### CODE REVIEW

**Comment by tdurieux** [comment]
ADD needs the diff file. Is coming has this?

**Comment by SophieHYe** [comment]
Hi @tdurieux ,
Thanks for the PR, Coming has diff files. I am merging your PR now.

**Comment by tdurieux** [comment]
Thus some changes were needed to include the diff. @martinezmatias could you say how to obtain the path to the diff

**Comment by martinezmatias** [comment]
Hi @tdurieux 
> could you say how to obtain the path to the diff

What do you mean with "the path to the diff"? The diff was computed some lines below to the place you call ADD (https://github.com/SpoonLabs/coming/blob/7dd16f893aefd1a79d75d70fffbf1c9a0fe349ec/src/main/java/fr/inria/coming/codefeatures/FeatureAnalyzer.java#L71). We keep the edit script on memory (e.g., the `diff` object) but we dont generate a file with a diff.

**Comment by SophieHYe** [comment]
Hi @tdurieux ,
Sorry I merged your PR too fastly before it completed.  I tried the previous version, the ADD features can not be generated.  The instance revision also points to the diff folder: 

To determine the diff folders:
```
 revision.getFolder();
```
To obtain the diff file pairs:
```
revision.getChildren();
```

**Pull request merged**
