### PR TITLE
Elixir is revised

### PR DESCRIPTION
**Pull request by khaes-kth**
Hi,
Elixir patterns & filters are revised and tested.
@martinezmatias @monperrus

### CODE REVIEW

**Comment by khaes-kth** [comment]
Hello @martinezmatias ,

Travis says:
The job exceeded the maximum log length, and has been terminated.

What can we do to fix it? Could you increase the limit? Should we turn off the logging?

**Comment by martinezmatias** [comment]
Hi @khaes-kth 
Thanks for this new feature!

> Should we turn off the logging?

It seems that the default log level is log4j.rootLogger=INFO.
The problem can be that there is a logging call in level info that is called several times, or even there is a sysout that would be removed or replaced by a log.



> Could you increase the limit? 
I am not aware, but I say we should fix the problem in our code (e.g., changing min log level, removing unnecessary logs, etc)

Regards
Matias

**Comment by khaes-kth** [comment]
The problem was that the final-result was printed by System.out and due to the large test suite it produced a huge log.
Now I am logging the result at the debug level and it is not printed by default because the default log level is INFO. We can also log it at INFO level and change the log-threshold if you think that would be better.

**Comment by martinezmatias** [comment]
Hi @khaes-kth 

I am not sure if replace the sysout from the  `StdOutput` by the log.debug, because the idea of that output is to print something at the end.
I would say that I would be necessary to change the toString of the sub-class of FinalResult that cause the large output. WDYT?

**Comment by khaes-kth** [comment]
Hi @martinezmatias ,

Yes, that's an other option. The problem is that I do not see anything that can be removed from the output without losing information. For example, what follows is the output for one diff:

```
FileDiff [diffFolder=C:\other\daneshgah\phd-kth\TB\coming\target\classes\repairability_test_files\Elixir\elixir1]
FineGrainDifftAnalyzer

-one
Update TypeReference at elixir:6
	float to double

PatternInstanceAnalyzer


----For Diff:Update TypeReference at elixir:6
	float to double

: number instances found: 1
ChangePatternInstance [actions=[Update TypeReference at elixir:6
	float to double
]]
RepairabilityAnalyzer


----For Diff:Update TypeReference at elixir:6
	float to double

: number instances found: 1
ChangePatternInstance [actions=[Update TypeReference at elixir:6
	float to double
]]
```

What do you think?

**Comment by martinezmatias** [comment]
Hi @khaes-kth
 
The sysout is called by the StdOutput processor, which is used by Coming by default (i.e., if no fillter is set).
One strategy that we could do is to create an EmptyOutput which basically does nothing.
I would say that:
1. When a user  uses Coming via command line, Coming uses, by default, the StdOutput. (So we should change the code to set the output according to)
2. Otherwise, it uses the emptyoutput processor. For example, the Travis Ci, which does not run the tool from a Jar, will print nothing.
(A correct way would be to configure travis to indicate Coming to use the emptyOuput, but, as it runs `mvn test` I am not sure how to pass as parameter that info)

(Note that, even the solution of passing to log.debug that single syso, it could be problematic for somebody that checkouts the project, run in and does not see nothing on the screen due to the default log level is INFO)

WDYT?

**Comment by khaes-kth** [comment]
Thank you @martinezmatias for your comments. I agree with all of them.

Do you have any idea how we can implement the second feature? (how to make Travis execution to use EmptyOutput). We might even be able to configure Travis to ignore logs (I am not a professional Travis user!)

Another (not very good) option would be to increase the log limit. Isn't it better to log more rather than log nothing in Travis?

**Comment by martinezmatias** [comment]
Hi @khaes-kth 

> Another (not very good) option would be to increase the log limit. Isn't it better to log more rather than log nothing in Travis?

That could be a nice solution, maybe in this post we have the solution: https://stackoverflow.com/questions/4782089/how-to-change-maven-logging-level-to-display-only-warning-and-errors (remember that travis calls `mvn test`)

A maybe dirty but easy to implement solution (related to point 1) could be:
1. Inside the main https://github.com/SpoonLabs/coming/blob/HEAD/src/main/java/fr/inria/coming/main/ComingMain.java#L128 we mark somewhere e.g. (ComingProperties) that the program was launched from the main.
2. Then we load the output processor, at https://github.com/SpoonLabs/coming/blob/HEAD/src/main/java/fr/inria/coming/main/ComingMain.java#L246 we check the mark: if it's `on' we add the StdOut (as done [here](https://github.com/SpoonLabs/coming/blob/HEAD/src/main/java/fr/inria/coming/main/ComingMain.java#L248)), otherwise no.

**Comment by khaes-kth** [comment]
Hi @martinezmatias 

I used sure-fire maven plugin [here](https://github.com/khaes-kth/coming/blob/revision/Elixir/pom.xml#L241) to pass the required argument while executing mvn test. When "mvn test" is executed by travis, "executed_by_travis" is set to true and an empty output is generated [here](https://github.com/khaes-kth/coming/blob/revision/Elixir/src/main/java/fr/inria/coming/main/ComingMain.java#L248).

**Comment by martinezmatias** [comment]
Hi @khaes-kth 
Great solution.
Thanks!
Matias

**Comment by khaes-kth** [comment]
Hi @martinezmatias 

Thanks!

**Pull request merged**
