### PR TITLE
[Repairibility]: fixed false positives of NPEfix on repogit4test data

### PR DESCRIPTION
**Pull request by niloofartrg**

### CODE REVIEW

**Comment by niloofartrg** [comment]
I am replacing prints with log but I don't know where to look in the Travis output to see if the problem is fixed, I don't find a max Travis limit error in the CI's output. @monperrus @martinezmatias

**Comment by monperrus** [comment]
CI is broken because of continuous deployment. Fixed it in https://github.com/SpoonLabs/coming/commit/c04b48629055c84dd39565330d033cf4aa4386e4.

**Comment by monperrus** [comment]
We're making progress, at least one build passes https://travis-ci.org/SpoonLabs/coming/builds/560932472

Merging to move forward

**Comment by niloofartrg** [comment]
what you merged has the changed for NPEfix and also log. Is that fine? I was trying to go back in the commits and create a separate PR for logs.

**Comment by monperrus** [comment]
> what you merged has the changed for NPEfix and also log. Is that fine?
not optimal, but still OK :-) it's important to keep momentum by merging good-enough pull requests.

**Pull request merged**
