### PR TITLE
[Draft] Time limit for git input mode

### PR DESCRIPTION
**Pull request by khaes-kth**
Users can set max_time_for_a_git_repo to set a time limit for when the input is a git repo. When the time spend on analysis goes over the limit, next commits will not be analyzed anymore.

### CODE REVIEW

**Comment by khaes-kth** [comment]
in the current implementation, it is not guaranteed that if a time_limit is set, the most recent commits will be analyzed before reaching the time limit. Check [here](https://github.com/khaes-kth/coming/blob/78f7a0f6025c1aeec3cd69b88178db31775146c7/src/main/java/fr/inria/coming/core/engine/RevisionNavigationExperiment.java#L116). So do not merge it yet please.

**Comment by martinezmatias** [comment]
Hi @khaes-kth 
Thanks for this nice feature. We had a similar one on Astor, but not here, so it's nice.

>  it is not guaranteed that if a time_limit is set, the most recent commits will be analyzed before reaching the time limit. Check here. 

I dont see the problem. Why the current implementation is not working fine?

> So do not merge it for now please.
Okey, tell me if you need something about.

Regards
Matias

**Comment by khaes-kth** [comment]
Hi @martinezmatias ,



> I dont see the problem. Why the current implementation is not working fine?

Let say the repo contains n commits. If max_nb_commit_analyze is set to m and max_time_for_a_git_repo is set to t seconds, Coming starts from the (n-m+1)_th_ commit and continues until all the (n-m+1)_th_ to (n)_th_ commits are analyzed or the time spend on the analysis is more than t seconds. So there is a possibility that only the commits (n-m+1)_th_ to (n-m+i)_th_ (i < m) are analyzed and time is over which means some of the most recent commits will not be analyzed.

This can be seen as a feature as it is or we can try to start the analysis from the (n)_th_ commit and go backward through the development history until reaching the (n-m+1)_th_ commit to make sure that the analyzed commits are the most recent ones.

However, I think if we have the list of all analyzed commits, that would be enough for the Repairability project we are working on right now. So I added this data to the output [here](https://github.com/khaes-kth/coming/blob/feature/git-time-limit/src/main/java/fr/inria/coming/core/entities/output/JSonPatternInstanceOutput.java#L38):

```
JsonArray analyzedRevisions = new JsonArray();
root.add("analyzed_revisions", analyzedRevisions);

	for (Object revision_commit : finalResult.getAllResults().keySet()) {
	analyzedRevisions.add(revision_commit.toString());
```

I am OK with the current version and if you think no more change is required, it is time for a merge. But if you think we should always analyze the most recent commits, I should see how we can do that.

**Comment by martinezmatias** [comment]
Hi @khaes-kth 

> So there is a possibility that only the commits (n-m+1)th to (n-m+i)th (i < m) are analyzed and time is over which means some of the most recent commits will not be analyzed.

That could happen, it's fine, which it should be very clear is to show a message that says something like "We reach the TIME_MAX of 1 hour and we analyzed X out of Y commits"

> we can try to start the analysis from the (n)th commit and go backward through the development history until reaching the (n-m+1)th commit to make sure that the analyzed commits are the most recent ones

Yes, that's another feature (BTW, really simple to implement).


> But if you think we should always analyze the most recent commits, I should see how we can do that.

I would say `no`: if we arrive to the TIMEOUT and there was not enough time to process the latest n commits, we should simply report the message. (The reverse order navigation would be another feature, not related to this one).

> I am OK with the current version and if you think no more change is required, it is time for a merge.

Perfect. I merge! Thanks a lot.

**Pull request merged**
