### PR TITLE
Analysis script

### PR DESCRIPTION
**Pull request by niloofartrg**

### CODE REVIEW

**Comment by monperrus** [comment]
could you mention the script at the appropriate place in the documentation?
thanks!

**Comment by sedflix** [comment]
Hey! 
I think it would be better if this script remains a part of the DRR repo. It's kind of separating the result analysis(on of very own data in DRR) and the actual module. Appropriate documentation about it are present there.

WDYT?

**Comment by monperrus** [comment]
> I think it would be better if this script remains a part of the DRR repo
maybe. I also like the idea to have a pure Java repo here.

> Appropriate documentation about it are present there.
where?

**Comment by sedflix** [comment]
> where? 

Oops. Sorry. I forgot to document the analyze script in [the README.md](https://github.com/SpoonLabs/coming/pull/113)(I just documented the fullcxt.py)

**Comment by monperrus** [comment]
would you document it in a PR? Thanks!

**Comment by monperrus** [comment]
let's close this PR and @niloofartrg will make a PR here with a documentation improvement.

**Pull request closed without merging**
