### PR TITLE
Generate unified diff for ADD

### PR DESCRIPTION
**Pull request by tdurieux**
Add for the minimal configuration of ADD, this configuration should be enough to compute all the metrics and patterns detection.

### CODE REVIEW

**Comment by martinezmatias** [comment]
Hi @tdurieux , thanks!
I didn't know that ADD needs the diff file. I thought it was enough with the Diff object computed by GT-Spoon.
For curiosity, For what is used the diff file?

**Comment by tdurieux** [comment]
The diff file is used to compute some metrics and also the single line pattern. 
It is used for additional information, it could be possible to remove it from add but why not to keep it :)

**Comment by martinezmatias** [comment]
Perfect, thanks for the clarification.
I would keep it on ADD, however, it could be nice to have the option to avoid compute them. 
Example (a simple idea): if you pass a `null` to `config.setDiffPath(tempFile.getAbsolutePath());` ADD does not compute nothing related to the diff.
That could allow us to improve the performance when we analyze thosands of commits and revisions.
WDYT?

**Comment by tdurieux** [comment]
this could be considered in the future

**Comment by martinezmatias** [comment]
perfect!

**Comment by martinezmatias** [comment]
Hi @tdurieux 
Just a question for curiosity: Was the ADD.1.1-snapshot version used by Coming generated from the ADD's master branch or from the backport branch from Martin's fork?
Thanks

**Comment by tdurieux** [comment]
the master branch

**Comment by martinezmatias** [comment]
Cool, thanks.
I will open an issue about what we have discuss yesterday and eventually a PR.

**Pull request merged**
