### PR TITLE
[Repairability] JGenProg

### PR DESCRIPTION
**Pull request by sedflix**

### CODE REVIEW

**Comment by sedflix** [comment]
Hi @martinezmatias ,

I will produce a mergeable version of this commit after NPEFix PR is merged. 

Since this PR includes more than one essential change, I think squashing all the commits to one(as done with other PR) would hide two essential commits(ie: `[Repairability] consider revisions with only one file modification` and `[Repairability] filter signature changed`). WDYT?

**Comment by martinezmatias** [comment]
Hi @sedflix 

> I will produce a mergeable version of this commit after NPEFix PR is merged.
Perfect, thanks.

> Since this PR includes more than one essential change, I think squashing all the commits to one(as done with other PR) would hide two essential commits

What about doing two PR?

**Comment by sedflix** [comment]
> What about doing two PRs?

I think it will be a bit tricky to split the current PR into two or more

**Comment by sedflix** [comment]
Hi @martinezmatias ,

I can try to split this into two PR but it would be tricky. 
I've tried to squash commits to a few essential ones and rebased so that squashing won't be required. Does this work? If not, I will try to split this into two.

I'll try to ensure one feature per PR thing from the next time.

**Pull request merged**
