### PR TITLE
JMutRepair tested and revised

### PR DESCRIPTION
**Pull request by khaes-kth**
JMutRepair tested against the ground-truth tests and also on android-async-http. Some parts of the implementation are revised.

### CODE REVIEW

**Comment by martinezmatias** [comment]
Hi @khaes-kth 
Thanks, ready to merge?

**Comment by khaes-kth** [comment]
Hi @martinezmatias ,

Do you know how I can avoid that all the commits that have been merged before be repeated in every new PR that I create? For example, this PR is only based on the last three commits listed here but as you can see the list contains 45 commits (the number of changed files is mentioned correctly, though).

(BTW, I think this PR is ready to be merged)

**Comment by martinezmatias** [comment]
Hi @khaes-kth 

> (BTW, I think this PR is ready to be merged)

Thanks. BTW, one new feature you can use is "Draft" pull request:
https://github.blog/2019-02-14-introducing-draft-pull-requests/
Thus, that allows to only merge when the PR is ready (not draft)

> Do you know how I can avoid that all the commits that have been merged before be repeated in every new PR that I create? For example, this PR is only based on the last three commits listed here but as you can see the list contains 45 commits (the number of changed files is mentioned correctly, though).

It seems that your folk has not the latest version from the upstream (which should be SpoonLabs/Coming):
The master branch of your folk is `This branch is 42 commits ahead, 1 commit behind SpoonLabs:master.`  I imagine that those 42 commits you are ahead correspond to those from PR https://github.com/SpoonLabs/coming/pull/190, and since the merge of that PR, integrated in the master in the commit [(this one)](https://github.com/SpoonLabs/coming/commit/f93fbc77cc997d23e6791a95ff5484741adbf07c) you are behind.
Thus, when you branched from that master and added 3 more commits, it has in total 45 commits.

**Comment by martinezmatias** [comment]
To continue the previous comment:

Which maybe you missed after the PR was merged was:
- 1) To do `git pull upstream master` (supposing that you have upstream pointing to SpoonLabs/Coming)

- 2) To update your master (i.e., in the folk) `git push origin master`

**Comment by khaes-kth** [comment]
> It seems that your folk has not the latest version from the upstream

You were right @martinezmatias . It's fixed now. Thanks a lot.



> BTW, one new feature you can use is "Draft" pull request

Yeah. I used it [once before](https://github.com/SpoonLabs/coming/pull/179). I'll use it more often.

A problem that I have now is that I cannot run all the tests on my PC (windows) so I have to create a pull request to make sure that all the tests are passed (I know this is the worst option to do this :-) ) That's because one of the libraries used in Coming creates a temporary file with a name that includes "->" character and cannot be saved on windows. I'll fix it in the problem in the library soon.

**Comment by martinezmatias** [comment]
Hi @khaes-kth 

> That's because one of the libraries used in Coming creates a temporary file with a name that includes "->" character and cannot be saved on windows.

Could you create an Issue describing that problem? Which is the library you found the problem?
Regards
Matias

**Pull request merged**
