### PR TITLE
[Nopol & jMutRepair] fine-tuning

### PR DESCRIPTION
**Pull request by sedflix**
- makes the tests for both Nopol and jMutRepair more comprehensive by adding new tests and test files
- improves jMutRepair patterns by a lot
- removes a reductant pattern in Nopol

### CODE REVIEW

**Comment by sedflix** [comment]
Hey @martinezmatias ,

This is in regard to the patterns for Nopol. Nopol either inserts an if-condition or updates an if-condition
I came up with the following patterns to detect an update in if-conditions.
```xml
<pattern name="if_condition_upd">

    <entity id="1" type="If"/>
    <entity id="2" type="*" role="condition">
        <parent parentId="1" distance="1"/>
    </entity>
    <entity id="4" type="*">
        <parent parentId="2" distance="1000000"/>
    </entity>
    <action entityId="4" type="*"/>

    <entity id="3" type="*" role="Then">
        <parent parentId="1" distance="1"/>
    </entity>
    <action entityId="3" type="UNCHANGED_HIGH_PRIORITY"/>
</pattern>
```

The problem with the above pattern is that it creates multiple instances for a single if-condition update.
For example, a single if-condition update results in the creation of the following instances:
```
[ChangePatternInstance [actions=[Insert VariableRead at com.google.javascript.jscomp.LightweightMessageFormatter:97                                                                              
        error                                                                                                                                                                                    
]], ChangePatternInstance [actions=[Update Literal at com.google.javascript.jscomp.LightweightMessageFormatter:98                                                                                
         to null                                                                                                                                                                                 
]], ChangePatternInstance [actions=[Move Literal from com.google.javascript.jscomp.LightweightMessageFormatter:98 to com.google.javascript.jscomp.LightweightMessageFormatter:97                 
        0                                                                                                                                                                                        
]], ChangePatternInstance [actions=[Delete TypeAccess at com.google.javascript.jscomp.LightweightMessageFormatter                                                                                
        com.google.javascript.jscomp.LightweightMessageFormatter                                                                                                                                 
]], ChangePatternInstance [actions=[Delete FieldRead at com.google.javascript.jscomp.LightweightMessageFormatter:97                                                                              
        excerpt                                                                                                                                                                                  
]], ChangePatternInstance [actions=[Delete TypeAccess at com.google.javascript.jscomp.LightweightMessageFormatter:97                                                                             
        SourceExcerpt.LINE                                                                                                                                                                       
]], ChangePatternInstance [actions=[Delete Invocation at com.google.javascript.jscomp.LightweightMessageFormatter:97                                                                             
        (excerpt.equals(SourceExcerpt.LINE))                                                                                                                                                     
]], ChangePatternInstance [actions=[Delete VariableRead at com.google.javascript.jscomp.LightweightMessageFormatter:98                                                                           
        charno                                                                                                                                                                                   
]], ChangePatternInstance [actions=[Delete BinaryOperator at com.google.javascript.jscomp.LightweightMessageFormatter:98                                                                         
        ( <= charno)                                                                                                                                                                             
]], ChangePatternInstance [actions=[Delete BinaryOperator at com.google.javascript.jscomp.LightweightMessageFormatter:97                                                                         
        ((excerpt.equals(SourceExcerpt.LINE)) && ( <= charno))                                                                                                                                   
]], ChangePatternInstance [actions=[Delete VariableRead at com.google.javascript.jscomp.LightweightMessageFormatter:98                                                                           
        charno                                                                                                                                                                                   
]], ChangePatternInstance [actions=[Delete VariableRead at com.google.javascript.jscomp.LightweightMessageFormatter:98                                                                           
        sourceExcerpt                                                                                                                                                                            
]], ChangePatternInstance [actions=[Delete Invocation at com.google.javascript.jscomp.LightweightMessageFormatter:98                                                                             
        (sourceExcerpt.length())                                                                                                                                                                 
]], ChangePatternInstance [actions=[Delete BinaryOperator at com.google.javascript.jscomp.LightweightMessageFormatter:98                                                                         
        (charno < (sourceExcerpt.length())) 
```
This results in 186 instances of if-upade instead of 22.

Right now, I think that this problem can be solved in the following manners(in order of my preference): 
- changing pattern specification such that it only considers one instance per if-update. But, I can't think of a way for it. Is it possible?
- use the repairability filter function.
- use the coming filter and hence maybe extend it?
- process all this in the Output Stage.

WDYT?

**Comment by sedflix** [comment]
And what is the role of ActionType `PER`?

**Comment by martinezmatias** [comment]
HI @sedflix 
> And what is the role of ActionType PER?

It means "permutation" of two elements. Currently it's not used because GumTree does not generate those actions in the current version.

**Comment by martinezmatias** [comment]
Hi @sedflix 

> it creates multiple instances for a single if-condition update

I get the point. I imagine that is different came from the fact that there are multiples changes inside the if condition, so Coming generates one instance per change.

> Right now, I think that this problem can be solved in the following manners(in order of my preference):
> changing pattern specification such that it only considers one instance per if-update. But, I can't think of a way for it. Is it possible?
> use the repairability filter function.
> use the coming filter and hence maybe extend it?
> process all this in the Output Stage.

Maybe this issue is related to the fact that the matcher is considering *all the operations* rather than the root (see [here](https://github.com/SpoonLabs/coming/blob/5304684426c848f2e836af992526a3654ad06d1e/src/main/java/fr/inria/coming/changeminer/analyzer/instancedetector/DetectorChangePatternInstanceEngine.java#L379) )
WDYT?
What do you think about considering only *roots* actions rather than *all* actions in the instance matching process? (not only related to this case)

**Comment by martinezmatias** [comment]
Should I merge this PR and continue the discussion in a new issue?

**Comment by sedflix** [comment]
> Should I merge this PR and continue the discussion in a new issue?

Yes.

**Comment by martinezmatias** [comment]
Thanks for the PR!

**Comment by sedflix** [comment]
> Maybe this issue is related to the fact that the matcher is considering all the operations rather than the root (see here )
WDYT?
What do you think about considering only roots actions rather than all actions in the instance matching process? (not only related to this case)

I like this option. I trying to make this work(as it would require a few changes in the pattern files). 
We will put a condition like "if the mode is repairability consider only root instances", right?

**Comment by martinezmatias** [comment]
Let's continue the discussion in the  new issue: https://github.com/SpoonLabs/coming/issues/94

**Pull request merged**
