### PR TITLE
[WIP] Nopol

### PR DESCRIPTION
**Pull request by sedflix**
Sorry for this messy PR. I choose HEAD~1 by mistake while checking out.

### CODE REVIEW

**Comment by sedflix** [comment]
Hi @martinezmatias ,

I'm having a bit of trouble in the "if condition update" pattern for nopol.
So just this can't find all instances of if condition update.
```
<entity id="2" type="*" role="condition">
        <parent parentId="1" distance="10"/>
 </entity>
 <action entityId="2" type="UPD"/>
```

But this results in finding too many instances of even a single if condition update.
```
    <entity id="2" type="*" role="condition">
        <parent parentId="1" distance="10"/>
    </entity>

    <entity id="4" type="Block">
            <parent parentId="2" distance="1000"/>
       </entity>
       <action entityId="4" type="*"/>
```

One of the ways to handle the later case is to consider only one instance per revision of a particular repair tool.

I've tried some other patterns configurations but they result in one of the above problems. Is there a better way to write patterns for this case? 

What do you think?

**Comment by martinezmatias** [comment]
Hi @sedflix 

> But the following pattern results in too many instances of even a single if-condition-update

But, are those instances correct? (Ratio False Positives).

Here, the point imho would be to focus on commits that only include changes on `if`, discarding commits with changes in other parts. Alternatively, you can put a threshold that indicates the max number of changes not related to the if (in the previous case would be zero ).

A suggestion for modeling the patterns could be to create different cases in test cases (invented cases) and to see what are the changes produced by GT-Spoon. Then, you try to model those changes using the pattern notation.

WDYT?

**Comment by sedflix** [comment]
Hey! 

I'm sorry for the late reply. I somehow missed the notif for this one.

> But, are those instances correct? (Ratio False Positives).

Yes, kind of. We want instances of if-condition update, but that approach ends up giving each change in the condition as one of the instances. So there are multiple instances of a single if-condition update. For example, these are the instances of a single if-condition update.
```
[ChangePatternInstance [actions=[Insert VariableRead at com.google.javascript.jscomp.LightweightMessageFormatter:97                                                                              
        error                                                                                                                                                                                    
]], ChangePatternInstance [actions=[Update Literal at com.google.javascript.jscomp.LightweightMessageFormatter:98                                                                                
         to null                                                                                                                                                                                 
]], ChangePatternInstance [actions=[Move Literal from com.google.javascript.jscomp.LightweightMessageFormatter:98 to com.google.javascript.jscomp.LightweightMessageFormatter:97                 
        0                                                                                                                                                                                        
]], ChangePatternInstance [actions=[Delete TypeAccess at com.google.javascript.jscomp.LightweightMessageFormatter                                                                                
        com.google.javascript.jscomp.LightweightMessageFormatter                                                                                                                                 
]], ChangePatternInstance [actions=[Delete FieldRead at com.google.javascript.jscomp.LightweightMessageFormatter:97                                                                              
        excerpt                                                                                                                                                                                  
]], ChangePatternInstance [actions=[Delete TypeAccess at com.google.javascript.jscomp.LightweightMessageFormatter:97                                                                             
        SourceExcerpt.LINE                                                                                                                                                                       
]], ChangePatternInstance [actions=[Delete Invocation at com.google.javascript.jscomp.LightweightMessageFormatter:97                                                                             
        (excerpt.equals(SourceExcerpt.LINE))                                                                                                                                                     
]], ChangePatternInstance [actions=[Delete VariableRead at com.google.javascript.jscomp.LightweightMessageFormatter:98                                                                           
        charno                                                                                                                                                                                   
]], ChangePatternInstance [actions=[Delete BinaryOperator at com.google.javascript.jscomp.LightweightMessageFormatter:98                                                                         
        ( <= charno)                                                                                                                                                                             
]], ChangePatternInstance [actions=[Delete BinaryOperator at com.google.javascript.jscomp.LightweightMessageFormatter:97                                                                         
        ((excerpt.equals(SourceExcerpt.LINE)) && ( <= charno))                                                                                                                                   
]], ChangePatternInstance [actions=[Delete VariableRead at com.google.javascript.jscomp.LightweightMessageFormatter:98                                                                           
        charno                                                                                                                                                                                   
]], ChangePatternInstance [actions=[Delete VariableRead at com.google.javascript.jscomp.LightweightMessageFormatter:98                                                                           
        sourceExcerpt                                                                                                                                                                            
]], ChangePatternInstance [actions=[Delete Invocation at com.google.javascript.jscomp.LightweightMessageFormatter:98                                                                             
        (sourceExcerpt.length())                                                                                                                                                                 
]], ChangePatternInstance [actions=[Delete BinaryOperator at com.google.javascript.jscomp.LightweightMessageFormatter:98                                                                         
        (charno < (sourceExcerpt.length())) 
```

> Here, the point imho would .... previous case would be zero ).

Right now, I'm not having problems in excluding commits "with changes in other parts". I will keep in mind to use those kinds of filters when necessary.

> A suggestion for modeling the patterns could be to create different cases in test cases (invented cases) and to see what are the changes produced by GT-Spoon.

I'm sorry. I didn't get this part. Can you please give an example?

**Comment by sedflix** [comment]
The last commit achieves 100% true-positive. But the problem of multiple instances still exists.

**Comment by martinezmatias** [comment]
Thanks @sedflix !

**Pull request merged**
