### PR TITLE
include prophet4j

### PR DESCRIPTION
**Pull request by ycaxgjd**
As discussed, Prophet4J will be included in this repo.

This time there would be no conflicts or CI errors
- updated code to get compatible with newer version of "org.eclipse.jgit"
- added one repo to make the 1.6-SNAPSHOT of "fr.inria.gforge.spoon.labs" available

### CODE REVIEW

**Comment by martinezmatias** [comment]
Thanks @ycaxgjd !

**Comment by martinezmatias** [comment]
Hi @ycaxgjd 
I reverted the merge. I saw you ignored some failing test cases that we had in the code base.
Could you take a look to those failures and then to create a new PR? (without ignoring the existing test cases)
Thanks
Matias

**Comment by ycaxgjd** [comment]
i will check them

**Comment by martinezmatias** [comment]
Thanks @ycaxgjd  (I ve just written an email)

**Pull request merged**
