### PR TITLE
JGenProg & Cardumen revised and tested against all ground-truth tests

### PR DESCRIPTION
**Pull request by khaes-kth**

### CODE REVIEW

**Comment by martinezmatias** [comment]
Hi @khaes-kth 

Thanks a lot for the PR. It's a great progress!
A minor suggestion would be -when it's possible- to generate shorter PR, specially in terms of files affected (not in number of commits, because afterward they are squashed): that could help to review the code and to discuss the solution adopted, etc.

**Comment by khaes-kth** [comment]
Hi @martinezmatias ,

Sure, I'll try to do that. However, in this PR some utility functions were renamed and this changed all the files using them. That's the main reason for the high number of files changed.

**Comment by martinezmatias** [comment]
Hi @khaes-kth 

> That's the main reason for the high number of files changed.

Yes, no problem, it happens to have large PR!

**Comment by khaes-kth** [comment]
Can you merge this PR @martinezmatias ?

**Comment by martinezmatias** [comment]
Hi @khaes-kth 
Done. Thanks a lot!
Cheers
Matias

**Comment by khaes-kth** [comment]
Thank you very much @martinezmatias

**Pull request merged**
