### PR TITLE
FP solving (NoPol & Elixir)

### PR DESCRIPTION
**Pull request by niloofartrg**

### CODE REVIEW

**Comment by monperrus** [comment]
oops, CI fails.

**Comment by niloofartarighattrg** [comment]
The failing test work locally, I don't know why it fails on Github. @monperrus

**Comment by monperrus** [comment]
@SophieHYe @jianguda could you help Niloofar with this CI problem? Thanks!

**Comment by SophieHYe** [comment]
I ran the test in Nilloofar's machine through IDE, it passed.
@niloofartrg What's the result of executing from maven, mvn test?

**Comment by niloofartarighattrg** [comment]
it passes the tests from mvn test. @SophieHYe

**Comment by monperrus** [comment]
CI fixed, merging.

Something strange is happening with the properties, I suspect it's because of the static field in ComingProperties

**Comment by niloofartrg** [comment]
Thanks.

**Pull request merged**
